skeLicense: 
imageRegistry:
  imagePullSecret: 
  host: "registry.syntasso.io"
  k8sHealthAgentImage:
    name: "syntasso/k8s-health-agent"

deployment:
  resources:
    limits:
      cpu:
      memory:
    requests:
      cpu:
      memory:
