{{- if and
    (hasKey .Values "cortexIntegration")
    (eq (default false .Values.cortexIntegration.enabled) true)
}}
{{- with .Values.cortexIntegration }}
{{- $config := required "cortexIntegration.config is required when cortexIntegration.enabled is true" .config }}
{{- $auth := include "ske-operator.cortexAuth" (dict "config" $config) | fromYaml }}
{{- if $auth.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $auth.secretName }}
  namespace: kratix-platform-system
type: Opaque
stringData:
  token: {{ $auth.token | quote }}
  url: {{ $auth.url | quote }}
{{- end }}
{{- end }}
{{- end }}
