{{- if .Values.skeDeployment.enabled }}
{{- if .Values.skeDeployment.additionalResources }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-additional-resources
  namespace: kratix-platform-system
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
spec:
  template:
    spec:
      serviceAccountName: ske-operator-controller-manager
      restartPolicy: Never
      containers:
        - name: deploy-resources
          image: {{ .Values.imageRegistry.host }}/{{ .Values.imageRegistry.skeOperatorImage.name }}:{{ .Chart.AppVersion }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -exu
              {{ range .Values.skeDeployment.additionalResources }}
              cat <<EOF | kubectl apply -f -
              {{ . | toYaml | indent 14 | trim }}
              EOF
              {{ end }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
              ephemeral-storage: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
              ephemeral-storage: 200Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
{{- end -}}
{{- end -}}
