{{- $createSecret := (include "ske-operator.createRegistrySecret" .) | trim -}}
{{- if and (eq $createSecret "true") .Values.imageRegistry.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageRegistry.imagePullSecret }}
  namespace: kratix-platform-system
{{- if or (not .Values.global.skeDeployment) (eq (default false .Values.global.skeDeployment.deleteOnUninstall) false) }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
