{{- if .Values.skeDeployment.enabled }}
{{- with .Values.skeDeployment }}
apiVersion: platform.syntasso.io/v1alpha1
kind: Kratix
metadata:
  name: kratix
  annotations:
    helm.sh/hook: post-install
    "helm.sh/hook-weight": "1"
spec:
  version: {{ .version | default "latest" }}
  resources:
    {{- toYaml .Values.skeDeployment.resources | nindent 2 }}
  tlsConfig:
    {{- if ( .tlsConfig.certManager.disabled | default false ) }}
    certSecretName: custom-kratix-platform-serving-cert
    {{- end }}
    certManager:
      disabled: {{ .tlsConfig.certManager.disabled | default false }}
{{- end }}
{{- end }}
