{{- if .Values.skeDeployment.tlsConfig.certManager.disabled -}}
apiVersion: v1
data:
  ca.crt: {{ .Values.skeDeployment.tlsConfig.webhookCACert | b64enc }}
  tls.crt: {{ .Values.skeDeployment.tlsConfig.webhookTLSCert | b64enc }}
  tls.key: {{ .Values.skeDeployment.tlsConfig.webhookTLSKey | b64enc }}
kind: Secret
metadata:
  name: custom-kratix-platform-serving-cert
  namespace: kratix-platform-system
{{- end -}}
