{{- if .Values.skeDeployment.enabled }}
{{- with .Values.skeDeployment }}
apiVersion: platform.syntasso.io/v1alpha1
kind: Kratix
metadata:
  name: kratix
  annotations:
    helm.sh/hook: post-install
spec:
  version: {{ .version | default "latest" }}
  tlsConfig:
    {{- if ( .tlsConfig.certManagerConfig.disabled | default false ) }}
    certSecretName: custom-kratix-platform-serving-cert
    {{- end }}
    certManagerConfig:
      disabled: {{ .tlsConfig.certManagerConfig.disabled | default false }}
{{- end }}
{{- end }}
