{{- if .Values.skeDeployment.enabled }}
{{- with .Values.skeDeployment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ske-deployment-config
  namespace: kratix-platform-system
data:
  ske-deployment: |
    apiVersion: platform.syntasso.io/v1alpha1
    kind: Kratix
    metadata:
      name: kratix
    spec:
      version: {{ .version | default "latest" }}
      {{- $dc := .deploymentConfig }}
      {{- with $dc.resources }}
      deploymentConfig:
        resources:
{{- toYaml . | nindent 10 }}
        {{- with $dc.nodeSelector }}
        nodeSelector:
{{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $dc.tolerations }}
        tolerations:
{{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $dc.affinity }}
        affinity:
{{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $dc.volumes }}
        volumes:
{{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with $dc.volumeMounts }}
        volumeMounts:
{{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      tlsConfig:
        {{- if ( .tlsConfig.certManager.disabled | default false ) }}
        certSecretName: {{ (.tlsConfig.webhookTLSSecretRef).name | default "custom-kratix-platform-serving-cert" }}
        metricsServerCertSecretName: {{ (.tlsConfig.metricsServerTLSSecretRef).name | default "custom-kratix-platform-metrics-server-cert" }}
        {{- end }}
        certManager:
          disabled: {{ .tlsConfig.certManager.disabled | default false }}
{{- if not .tlsConfig.certManager.disabled }}
  {{- with .tlsConfig.certManager.issuerRef }}
    {{- if and .name .kind }}
          issuerRef:
            kind: {{ .kind }}
            name: {{ .name }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
