{{- if and .Values.skeDeployment.tlsConfig.certManager.disabled (not .Values.skeDeployment.tlsConfig.webhookTLSSecretRef) -}}
apiVersion: v1
data:
  ca.crt: {{ .Values.skeDeployment.tlsConfig.webhookCACert | default "" | b64enc }}
  tls.crt: {{ .Values.skeDeployment.tlsConfig.webhookTLSCert | default "" | b64enc }}
  tls.key: {{ .Values.skeDeployment.tlsConfig.webhookTLSKey | default "" | b64enc }}
kind: Secret
metadata:
  name: custom-kratix-platform-serving-cert
  namespace: kratix-platform-system
{{- end }}
{{ if and .Values.skeDeployment.tlsConfig.certManager.disabled (not .Values.skeDeployment.tlsConfig.metricsServerTLSSecretRef) }}
---
apiVersion: v1
data:
  ca.crt: {{ .Values.skeDeployment.tlsConfig.metricsServerCACert | default "" | b64enc }}
  tls.crt: {{ .Values.skeDeployment.tlsConfig.metricsServerTLSCert | default "" | b64enc }}
  tls.key: {{ .Values.skeDeployment.tlsConfig.metricsServerTLSKey | default "" | b64enc }}
kind: Secret
metadata:
  name: custom-kratix-platform-metrics-server-cert
  namespace: kratix-platform-system
{{- end }}
{{ if and .Values.skeDeployment.tlsConfig.certManager.disabled .Values.skeDeployment.tlsConfig.platformManagerCACert (not .Values.skeDeployment.tlsConfig.platformManagerTLSSecretRef) }}
---
apiVersion: v1
data:
  ca.crt: {{ .Values.skeDeployment.tlsConfig.platformManagerCACert | default "" | b64enc }}
  tls.crt: {{ .Values.skeDeployment.tlsConfig.platformManagerTLSCert | default "" | b64enc }}
  tls.key: {{ .Values.skeDeployment.tlsConfig.platformManagerTLSKey | default "" | b64enc }}
kind: Secret
metadata:
  name: custom-kratix-platform-manager-cert
  namespace: kratix-platform-system
{{- end -}}
