apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-health-agent-config
  namespace: k8s-health-agent-system
data:
  HEALTH_CHECK_ADAPTER_IMG: '{{ .Values.imageRegistry.host }}/{{ coalesce .Values.imageRegistry.healthAgentImage.name .Values.imageRegistry.k8sHealthAgentImage.name }}:{{ .Chart.AppVersion }}'