apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k8s-health-agent
    control-plane: controller-manager
  name: k8s-health-agent-controller-manager
  namespace: k8s-health-agent-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-bind-address=:8443
        - --leader-elect
        - --health-probe-bind-address=:8081
        command:
        - /manager
        env:
        - name: HEALTH_CHECK_ADAPTER_IMG
          valueFrom:
            configMapKeyRef:
              key: HEALTH_CHECK_ADAPTER_IMG
              name: k8s-health-agent-config
        image: '{{ .Values.imageRegistry.host }}/{{ .Values.imageRegistry.k8sHealthAgentImage.name
          }}:{{ .Chart.AppVersion }}'
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: '{{ .Values.deployment.resources.limits.cpu | default "500m"  }}'
            memory: '{{ .Values.deployment.resources.limits.memory | default "128Mi"  }}'
          requests:
            cpu: '{{ .Values.deployment.resources.requests.cpu | default "10m"  }}'
            memory: '{{ .Values.deployment.resources.requests.memory | default "64Mi"  }}'
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
      - name: '{{ .Values.imageRegistry.imagePullSecret | default "syntasso-registry" }}'
      securityContext:
        runAsNonRoot: true
      serviceAccountName: k8s-health-agent-controller-manager
      terminationGracePeriodSeconds: 10
