apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k8s-health-agent
    control-plane: controller-manager
  name: k8s-health-agent-system