apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k8s-health-agent
  name: k8s-health-agent-controller-manager
  namespace: k8s-health-agent-system