apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: k8s-health-agent-manager
    app.kubernetes.io/instance: k8s-health-agent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k8s-health-agent
    app.kubernetes.io/part-of: ske-platform
    control-plane: controller-manager
  name: k8s-health-agent-controller-manager
  namespace: k8s-health-agent-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: k8s-health-agent-manager
      app.kubernetes.io/instance: k8s-health-agent
      app.kubernetes.io/part-of: ske-platform
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/component: k8s-health-agent-manager
        app.kubernetes.io/instance: k8s-health-agent
        app.kubernetes.io/part-of: ske-platform
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --metrics-bind-address=:8443
            - --leader-elect
            - --health-probe-bind-address=:8081
          command:
            - /manager
          env:
            - name: HEALTH_CHECK_ADAPTER_IMG
              valueFrom:
                configMapKeyRef:
                  key: HEALTH_CHECK_ADAPTER_IMG
                  name: k8s-health-agent-config
            - name: SUCCESSFUL_JOBS_HISTORY_LIMIT
              value: "3"
            - name: FAILED_JOBS_HISTORY_LIMIT
              value: "1"
          image: registry.syntasso.io/syntasso/k8s-health-agent:v0.4.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: k8s-health-agent-controller-manager
      terminationGracePeriodSeconds: 10
