apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-controller
  namespace: backstage-controller-system
  labels:
    app.kubernetes.io/name: backstage-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backstage-controller
    spec:
      serviceAccountName: backstage-controller
      containers:
        - name: manager
          image: registry.syntasso.io/syntasso/backstage-controller:v0.3.0
          imagePullPolicy: IfNotPresent
