apiVersion: v2
name: ske-destination
description: A Helm chart for installing flux, configuring it to pull down from Kratix and optionally installing SKE features
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.11.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"
dependencies:
  - name: flux2
    # only install flux if specified in values file
    condition: installFlux
    version: 2.5.1
  - name: k8s-health-agent
    # only install Health Agent if specified in values file
    condition: k8sHealthAgent.enabled
    version: 0.11.0
    repository: https://syntasso.github.io/helm-charts
