{{- if not .Values.imageRegistry.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: syntasso-registry
  namespace: kratix-platform-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}