#!/usr/bin/env bash

kratixDist="${1:?Please provide the path to the Kratix distribution}"

root=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )

CHART_CRDS=$root/kratix/crds/platform_kratix_io_crds.yaml
CHART_DISTRIBUTION=$root/kratix/templates/distribution.yaml

yq 'select(.kind == "CustomResourceDefinition")' ${kratixDist} > ${CHART_CRDS}
yq 'select(.kind != "CustomResourceDefinition")' ${kratixDist} > ${CHART_DISTRIBUTION}

