#!/usr/bin/env bash

set -euxo pipefail

function main() {
  root=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )

  # Download the latest Portal Controller release tag
  latest_release="$(gh release list --repo=syntasso/enterprise-kratix --exclude-pre-releases --order desc --json tagName --jq "[ .[] | select(.tagName | match(\"ske-portal-controller\")) ][0].tagName")"
  if [ -z "$latest_release" ]; then
    echo "No release found for ske-portal-controller"
    exit 1
  fi

  export latest_version=${latest_release#"ske-portal-controller-"}

  yq -i '.portalIntegration.version = strenv(latest_version)' "${root}/ske-operator/values.yaml"
}

main
