{{- define "patch" }}
spec:
  template:
    spec:
      containers:
        {{- .container | list | toYaml | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
{{- end }}

{{- define "containerPatch" }}
{{- if .Values.image }}
image: {{ .Values.image | quote }}
{{- end }}
{{- with .Values.resources }}
resources:
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}

{{- $manifest := .Files.Get "files/deployment.yaml" | fromYaml }}
{{- $container := index $manifest.spec.template.spec.containers 0
                    | merge (include "containerPatch" . | fromYaml) }}
{{- $_ := set $manifest.spec.template "spec"
              (omit $manifest.spec.template.spec "containers") }}

{{- $manifest
      | merge (include "patch" (merge . (dict "container" $container)) | fromYaml)
      | toYaml }}
