# [DEPRECATED] Use additionalResources instead
{{- range .Values.destinations }}
---
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: {{ .name }}
  labels: {{ toYaml .labels | nindent 4 }}
spec:
  path: {{ required "destination path is required" .path }}
  {{- with .filepath }}
  filepath:
    mode: {{ .mode | default "nestedByMetadata" }}
  {{- end}}
  stateStoreRef:
    name: {{ .stateStoreRef.name }}
    kind: {{ .stateStoreRef.kind }}
  strictMatchLabels: {{ .strictMatchLabels | default false}}
{{ end }}
