apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
    control-plane: controller-manager
  name: kratix-platform-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-controller-manager
  namespace: kratix-platform-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-leader-election-role
  namespace: kratix-platform-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - platform.kratix.io
    resources:
      - bucketstatestores
      - destinations
      - gitstatestores
      - healthrecords
      - promisereleases
      - promises
      - workplacements
      - works
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - platform.kratix.io
    resources:
      - bucketstatestores/finalizers
      - destinations/finalizers
      - gitstatestores/finalizers
      - healthrecords/finalizers
      - promisereleases/finalizers
      - promises/finalizers
      - workplacements/finalizers
      - works/finalizers
    verbs:
      - update
  - apiGroups:
      - platform.kratix.io
    resources:
      - bucketstatestores/status
      - destinations/status
      - gitstatestores/status
      - healthrecords/status
      - promisereleases/status
      - promises/status
      - workplacements/status
      - works/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - roles
    verbs:
      - bind
      - create
      - delete
      - escalate
      - get
      - list
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-metrics-auth-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-leader-election-rolebinding
  namespace: kratix-platform-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kratix-platform-leader-election-role
subjects:
  - kind: ServiceAccount
    name: kratix-platform-controller-manager
    namespace: kratix-platform-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kratix-platform-manager-role
subjects:
  - kind: ServiceAccount
    name: kratix-platform-controller-manager
    namespace: kratix-platform-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kratix-platform-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: kratix-platform-controller-manager
    namespace: kratix-platform-system
---
apiVersion: v1
data:
  PIPELINE_ADAPTER_IMG: syntasso.docker.scarf.sh/syntasso/kratix-platform-pipeline-adapter@sha256:f3c684eece4e793ea8dafa1b757719ff796a23f5ae4fc0efc3a27d3a52683d81
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-pipeline-adapter-config
  namespace: kratix-platform-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k8s-health-agent
    control-plane: controller-manager
  name: kratix-platform-controller-manager-metrics-service
  namespace: kratix-platform-system
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: kratix
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-webhook-service
  namespace: kratix-platform-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
    control-plane: controller-manager
  name: kratix-platform-controller-manager
  namespace: kratix-platform-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kratix-manager
      app.kubernetes.io/instance: kratix-platform
      app.kubernetes.io/part-of: kratix
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kratix-manager
        app.kubernetes.io/instance: kratix-platform
        app.kubernetes.io/part-of: kratix
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --metrics-bind-address=:8443
            - --health-probe-bind-address=:8081
            - --leader-elect
          command:
            - /manager
          env:
            - name: PIPELINE_ADAPTER_IMG
              valueFrom:
                configMapKeyRef:
                  key: PIPELINE_ADAPTER_IMG
                  name: kratix-platform-pipeline-adapter-config
          image: syntasso.docker.scarf.sh/syntasso/kratix-platform@sha256:04ee9cbb5e4a1e8af69a93d150b2bb1f4384cc6ade4e34098982551fd3501ea3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /tmp/k8s-metrics-server/serving-certs
              name: metrics-certs
              readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kratix-platform-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
        - name: metrics-certs
          secret:
            items:
              - key: ca.crt
                path: ca.crt
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
            optional: false
            secretName: metrics-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: kratix
    app.kubernetes.io/instance: metrics-server-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-metrics-server-cert
  namespace: kratix-platform-system
spec:
  dnsNames:
    - kratix-platform-controller-manager-metrics-service.kratix-platform-system.svc
    - kratix-platform-controller-manager-metrics-service.kratix-platform-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kratix-platform-selfsigned-issuer
  secretName: metrics-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: kratix
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-serving-cert
  namespace: kratix-platform-system
spec:
  dnsNames:
    - kratix-platform-webhook-service.kratix-platform-system.svc
    - kratix-platform-webhook-service.kratix-platform-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kratix-platform-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: kratix
    app.kubernetes.io/instance: selfsigned-issuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: issuer
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-selfsigned-issuer
  namespace: kratix-platform-system
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kratix-platform-system/kratix-platform-serving-cert
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: kratix
    app.kubernetes.io/instance: mutating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mutatingwebhookconfiguration
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: kratix-platform-webhook-service
        namespace: kratix-platform-system
        path: /mutate-platform-kratix-io-v1alpha1-destination
    failurePolicy: Fail
    name: mdestination.kb.io
    rules:
      - apiGroups:
          - platform.kratix.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - destinations
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: kratix-platform-webhook-service
        namespace: kratix-platform-system
        path: /mutate-platform-kratix-io-v1alpha1-promise
    failurePolicy: Fail
    name: mpromise.kb.io
    rules:
      - apiGroups:
          - platform.kratix.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - promises
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kratix-platform-system/kratix-platform-serving-cert
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: kratix
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/part-of: kratix
  name: kratix-platform-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: kratix-platform-webhook-service
        namespace: kratix-platform-system
        path: /validate-platform-kratix-io-v1alpha1-destination
    failurePolicy: Fail
    name: vdestination.kb.io
    rules:
      - apiGroups:
          - platform.kratix.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - destinations
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: kratix-platform-webhook-service
        namespace: kratix-platform-system
        path: /validate-platform-kratix-io-v1alpha1-promise
    failurePolicy: Fail
    name: vpromise.kb.io
    rules:
      - apiGroups:
          - platform.kratix.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - promises
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: kratix-platform-webhook-service
        namespace: kratix-platform-system
        path: /validate-platform-kratix-io-v1alpha1-promiserelease
    failurePolicy: Fail
    name: vpromiserelease.kb.io
    rules:
      - apiGroups:
          - platform.kratix.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - promisereleases
    sideEffects: None
