apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kratix.serviceAccountName" . }}
  namespace: kratix-platform-system
  labels:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}