name: Update SKE Operator

on:
  push:
    branches:
      - '**'  # Runs on any branch
    paths: ['ske-gui/**', 'tests/**']
  workflow_dispatch:
    inputs:
      ssh_session:
        type: boolean
        description: 'Run the build with tmate debugging.'
        required: false
        default: false

jobs:
  update-ske-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CR_TOKEN }}

      - name: Configure Git
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git config user.name "syntassodev"
          git config user.email "kratix@syntasso.io"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kind
        uses: helm/kind-action@v1
        with:
          version: 'v0.20.0' # Use the desired version of Kind
          cluster_name: "platform"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Ginkgo CLI
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
        env:
          PATH: ${{ env.PATH }}:/home/runner/go/bin

      - name: Start tmate ssh debugging session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.ssh_session }}
        with:
          limit-access-to-actor: true
          detached: true

      - name: Update Chart
        run: |
          ./scripts/update-ske-gui
        env:
          GH_TOKEN: ${{ secrets.CR_TOKEN }}
          SKE_LICENSE_TOKEN: ${{ secrets.SKE_LICENSE_TOKEN }}

      - name: Commit and push changes
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git add .
          git commit -m "feat: update SKE GUI to the latest released version"
          git push
