name: Update Backstage Controller

on:
  workflow_dispatch:

jobs:
  update-backstage-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CR_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Configure Git
        run: |
          git config user.name "syntassodev"
          git config user.email "kratix@syntasso.io"

      - name: Update chart, template and crds
        run: |
          ./scripts/update-backstage-controller
        env:
          GH_TOKEN: ${{ secrets.CR_TOKEN }}

      - name: Commit and push changes
        run: |
          if [ -z "$(git status --porcelain backstage-controller/ )" ]; then
            echo "no changes to commit; exiting"
            exit 0
          fi
          git add .
          git commit -m "feat: update backstage-controller to the latest released version"
          git push
